---
title: "Tidyverse"
author: "Sadi Tomtulu"
---

# Data Science at TUHH ------------------------------------------------------
# SALES ANALYSIS ----

# 1.0 Load libraries ----

```{r}
library(tidyverse)


library(readxl)

library(lubridate)
```

# 2.0 Importing Files ----

```{r}
bikes <- read_excel(path = "C:/Users/sedit/Desktop/SadiR/ss23-bdsb-Sadtom98/content/01_journal/01_tidyverse_files/Bikes/01_bike_sales/01_raw_data/bikes.xlsx")


bikeshops <- read_excel(path = "C:/Users/sedit/Desktop/SadiR/ss23-bdsb-Sadtom98/content/01_journal/01_tidyverse_files/Bikes/01_bike_sales/01_raw_data/bikeshops.xlsx")


orderlines <- read_excel("C:/Users/sedit/Desktop/SadiR/ss23-bdsb-Sadtom98/content/01_journal/01_tidyverse_files/Bikes/01_bike_sales/01_raw_data/orderlines.xlsx")
```

# 3.0 Examining Data ----

```{r}
glimpse(orderlines)
```

# 4.0 Joining Data ----

```{r}
bike_orderlines <- left_join(orderlines, bikes, by = c("product.id" = "bike.id")) %>% left_join(bikeshops, by = c("customer.id" = "bikeshop.id"))
```

# 5.0 Wrangling Data ----

```{r}
bike_orderlines_wrangled <- bike_orderlines %>%
  separate(col    = location,
           into   = c("City", "State"), sep = ",") %>% mutate(total.price = price * quantity) %>%
set_names(names(.) %>% str_replace_all("\\.", "_"))
```

# 6.0 Business Insights ----
# 6.1 Sales by State ----



```{r}
sales_by_state <- bike_orderlines_wrangled %>%
 
  # Select columns
  select(order_date, total_price, State) %>%

  # Add year column
  mutate(year = year(order_date)) %>%
 
  # Grouping by year and summarizing sales
  group_by(State) %>% 
  summarize(sales = sum(total_price)) %>%
 
  # Optional: Add a column that turns the numbers into a currency format 
  # (makes it in the plot optically more appealing)
  # mutate(sales_text = scales::dollar(sales)) <- Works for dollar values
  mutate(state_text = scales::dollar(sales, big.mark = ".", 
                                     decimal.mark = ",", 
                                     prefix = "", 
                                     suffix = " €"))

sales_by_state
```


# Step 1 - Manipulate

# Step 2 - Visualize


```{r}
sales_by_state %>%
ggplot(aes(x = State, y = sales, fill = State)) +

  # Geometries
  geom_col()
```


# 6.2 Sales by Year and State ----

# Step 1 - Manipulate

# Step 2 - Visualize



# 7.0 Writing Files ----

# 7.1 Excel ----

# 7.2 CSV ----

# 7.3 RDS ----

